"""empty message

Revision ID: e18b852170de
Revises: def7cbca0001
Create Date: 2021-03-05 01:36:20.147107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18b852170de'
down_revision = 'def7cbca0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_palette', sa.Column('backgroundImageId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'color_palette', 'background_images', ['backgroundImageId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'color_palette', type_='foreignkey')
    op.drop_column('color_palette', 'backgroundImageId')
    # ### end Alembic commands ###
