"""empty message

Revision ID: f66c40ff5836
Revises: 
Create Date: 2021-03-09 11:35:39.946588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66c40ff5836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.String(length=100), nullable=True),
    sa.Column('imageUrl', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('color_palette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backgroundImageId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('palette', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['backgroundImageId'], ['background_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backgroundImgId', sa.Integer(), nullable=True),
    sa.Column('pageLayoutId', sa.Integer(), nullable=True),
    sa.Column('colorPaletteId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('pageName', sa.String(length=100), nullable=True),
    sa.Column('partnerOne', sa.String(length=100), nullable=True),
    sa.Column('partnerTwo', sa.String(length=100), nullable=True),
    sa.Column('weddingDateTime', sa.DateTime(), nullable=True),
    sa.Column('venueName', sa.String(length=255), nullable=True),
    sa.Column('venueAddress', sa.String(length=255), nullable=True),
    sa.Column('venueCity', sa.String(length=255), nullable=True),
    sa.Column('venueState', sa.String(length=255), nullable=True),
    sa.Column('venueZip', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('profileImg', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['backgroundImgId'], ['background_images.id'], ),
    sa.ForeignKeyConstraint(['colorPaletteId'], ['color_palette.id'], ),
    sa.ForeignKeyConstraint(['pageLayoutId'], ['page_layout.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userPageId', sa.Integer(), nullable=True),
    sa.Column('firstName', sa.String(length=150), nullable=False),
    sa.Column('lastName', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.Column('numberAttending', sa.Integer(), nullable=False),
    sa.Column('foodAllergies', sa.Boolean(), nullable=False),
    sa.Column('foodAllergiesDescription', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['userPageId'], ['user_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('user_page')
    op.drop_table('color_palette')
    op.drop_table('users')
    op.drop_table('page_layout')
    op.drop_table('background_images')
    # ### end Alembic commands ###
