"""empty message

Revision ID: def7cbca0001
Revises: 4799015085e7
Create Date: 2021-03-05 00:16:37.464295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def7cbca0001'
down_revision = '4799015085e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background_images', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('color_palette', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color_palette', 'name')
    op.drop_column('background_images', 'name')
    # ### end Alembic commands ###
